<?php

function sutunam_menu()
{

  $items['admin/config/templates'] = array(
    'title' => 'templates setting',
    'discription' => 'templates setting ',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sutunam_setting_form'),
    'access arguments' => array('access administration page'),
    'weight' => 2
  );

  return $items;
}

function sutunam_setting_form($form, &$form_state)
{
  $form = array();

  $form['backgroundimage'] = array(
    '#type' => 'managed_file',
    '#name' => 'backgroundimage_image',
    '#title' => t('upload image, huh!'),
    '#default_value' => variable_get('backgroundimage', ''),
    '#description' => t("Here you can upload an image to the background!"),
    '#required' => TRUE,
    '#upload_location' => 'public://backgroundimage/'
  );
  $form['#submit'][] = 'sutunam_form_submit';
  return system_settings_form($form);
}

function sutunam_form_submit($form, $form_state) {
  $form['backgroundimage']['#file']->status = FILE_STATUS_PERMANENT;
  file_save($form['backgroundimage']['#file']);
}



/**
Implementation of hook_views_query_alter()
 **/
function sutunam_views_query_alter(&$view, &$query) {

    /*if($view->name == "tours_list") {
        // User the provider uid to make the results distinct: using a taxonomy field for
        // keyword searches brings up multiple results.
        //foreach($query->fields as $key => $field) {
         //   $query->fields[$key]['aggregate'] = TRUE;
        //}
        $query->fields['nid']['aggregate'] = TRUE;
        $query->add_groupby('nid');

    }*/
}

function sutunam_views_pre_execute(&$view)
{
    if($view->name == 'tours_list')
    {
        $view->build_info['query']->groupby('nid');
    }
}

/**
 *  Implementation of hook_form_alter().
 */

function sutunam_form_views_exposed_form_alter(&$form, &$form_state) {

    if($form['#id'] == 'views-exposed-form-search-tour-page') {
        $form['field_departure_day_value']['value']['#date_format'] = 'd/m/Y';
        $form['field_departure_day_value_1']['value']['#date_format'] = 'd/m/Y';
    }

}

function sutunam_node_view($node, $view_mode, $langcode) {

    if($node->type=='tour'){
        $update=false;
        $t=strtotime("midnight", time());
        if(isset($node->field_departure_day[LANGUAGE_NONE])){
            $items=$node->field_departure_day[LANGUAGE_NONE];
            foreach($items as $key=>$value){
                $t_current=strtotime($value['value']);
                if($t>$t_current){
                    unset($node->field_departure_day[LANGUAGE_NONE][$key]);
                    $update=true;
                }
            }
        }


        if(isset($node->field_prices[LANGUAGE_NONE])){
            //$prices_clone;
            $items=$node->field_prices[LANGUAGE_NONE];
            foreach($items as $entKey => $entVal){
                $field_collection = field_collection_field_get_entity($entVal);
                $t_current=strtotime($field_collection->field_start_date[LANGUAGE_NONE][0]['value']);
                if($t>$t_current){
                    unset($node->field_prices[LANGUAGE_NONE][$entKey]);
                    $update=true;
                    $field_collection->delete();
                }
            }
        }
        if ($update) field_attach_update('node', $node);
    }
}